# hugo.toml for my Hugo Site

baseURL = 'https://about.princetonstrong.online'
languageCode = 'en-us'
theme = "hugo-themes-nightfall"

[params.styles]
color = "orange"

[menu]
  [[menu.header]]
    name = "about"
    weight = 0
    url = "me"

[params]
user = "$USER"
hostname = "online"
footerHtml = '© 2025, CC-0, Princeton A. Strong.'
  [params.author]
    name = "Princeton A. Strong"  # Website and RSS feed author
    email = "princeton.strong@outlook.com"  # RSS feed email address

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/borninthedark"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 1
name = "credly"
url = "https://www.credly.com/users/princeton-strong"
target = "_blank"
aria = "Credly Profile"

[[params.social]]
key = 2
name = "email"
url = "mailto:princeton.strong@outlook.com"
aria = "My e-Mail Address"

